### ISSUE TITLE
Support for Sylius refunds?

### ISSUE THREAD

**Issue by michael-bouvy** [alma/AlmaSyliusPaymentPlugin#1]
This plugins looks promising!

Do you have plans regarding implementation of refunds within this plugin (https://docs.sylius.com/en/latest/book/orders/refunds.html)?

Also, does this plugin support authorize then capture?

Thanks!

**Comment by syjust-alma** [comment]
Hi @michael-bouvy ,

At this time, refund implementation is not planned (but this feature is in our backlog).

Our Api does not support Authorize then Capture for the moment... so it will not implement this behavior for the moment.
