### ISSUE TITLE
Any plan to support PHP 8 ?

### ISSUE THREAD

**Issue by arnaud-ritti** [alma/AlmaSyliusPaymentPlugin#3]
Do you have plan to support PHP 8.0 ? It will be awesome.

**Comment by syjust-alma** [comment]
We plan to analysis a support for PHP 8 compatibility before the end of the year.

We have to maintain our plugin with older PHP versions (at least PHP 7.2).

Just for our information, could you tell us which Sylius version did you use ?

**Comment by samiball** [comment]
Hi,
We user Sylius 1.11 and PHP 8 is required,

**Comment by titi60** [comment]
same issue there.

**Comment by syjust-alma** [comment]
thank you for your feedback @samiball .
@titi60 / @arnaud-ritti , could you tell us which version of Sylius are you using please ?

**Comment by titi60** [comment]
Sylius 1.11.6

**Comment by samiball** [comment]
Sylius 1.11.6 too

**Comment by brtes** [comment]
Hello ! Same question here, with a Sylius 1.11.7 !

**Comment by Vincent-Mazel** [comment]
Hi, any news concerning PHP 8 compatibility ? Is the support still planned before the end of the year ?

**Comment by syjust-alma** [comment]
Hi all, sorry for the late answer. (We just didn't take the time to test before 😞 )

We just released [v1.3.0](https://github.com/alma/AlmaSyliusPaymentPlugin/releases/tag/v1.3.0) that's works fine with PHP 8 & Sylius 1.11 (tested under SF 5.4).
